[pytest]
pythonpath = . playwright
addopts = --base-url=https://babyrefil.vercel.app/ --alluredir=allure-results --screenshot=on --video=retain-on-failure --tracing=retain-on-failure
markers =
    e2e: end-to-end test
    